#!/bin/bash

# ***** Modifier les paramètres ci-dessous *****

path_pool='/home/lisk/pool/' 				# Chemin absolu vers la pool
path_psql='/home/lisk/lisk-main/pgsql/bin/' 		# Chemin absolu executables postgresql de lisk

# les delegates sur lesquels on recherche les votants, on peut en mettre tant qu'on veut, pour sponsorer des potes
declare -a pubkey=('32f20bee855238630b0f791560c02cf93014977b4b25c19ef93cd92220390276' 'de918e28b554600a81cbf119abf5414648b58a8efafbc3b0481df0242684dc1b' '6b221c994ba2a69d8893f59a55431dd3e94327830f8818fc7fbffdbbb55b6fa9')
pool_delegate='liberspirita'			# nom du delegate qui forge la pool
taulier='7695675674841127110L'			# Adresse du patron de la pool, qui recevra les gains hors redistribution. Ce compte doit voter la pool pour que ça marche
tx_redistribution='60'				#taux de redistribution ex: 60 = 60 aux poolers, 40% au taulier
min_balance='100000000000' 			# Solde minimum des votants à comptabiliser. Pour éviter les morts ou dormants.

