#!/bin/bash
# **********************************************
# ***** Ajustez les paramètres ci-dessous *****
# **********************************************

# Chemin absolu vers la pool. Doit terminer par un /
path_pool='/home/lisk/lisk-basic-pool/'

# Chemin absolu executables postgresql de lisk. Doit terminer par un /
path_psql='/home/lisk/lisk-test/pgsql/bin/'

#base postgresql de lisk
psql_db='lisk_test'

# Ficher de la base SQLite3
db_sqlite='db_pool'

# les delegates sur lesquels on recherche les votants, on peut en mettre tant qu'on veut, pour sponsorer des potes
declare -a pubkey=('ab5146c3d62747f6372f5b35ca68ff85dccba9094526f84cd557133d395a8a7d' 'de918e28b554600a81cbf119abf5414648b58a8efafbc3b0481df0242684dc1b' '6b221c994ba2a69d8893f59a55431dd3e94327830f8818fc7fbffdbbb55b6fa9')

# nom du delegate qui forge la pool
pool_delegate='liberspirita'

# Adresse du patron de la pool, qui recevra les gains hors redistribution. Ce compte doit voter la pool pour que ça marche
taulier='7695675674841127110L'

#taux de redistribution aux poolers
tx_redistribution='60'

# Solde minimum des votants à comptabiliser. Pour éviter les morts ou dormants.
min_balance='0'

